// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvJDRK-3krXffjq29rALOYhNs42PwIudk',
    appId: '1:661269225469:web:4967f6581407e2d8cb4394',
    messagingSenderId: '661269225469',
    projectId: 'whatsappclone-94efa',
    authDomain: 'whatsappclone-94efa.firebaseapp.com',
    storageBucket: 'whatsappclone-94efa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDLrzKCHX9bdEoo0mvP_lr-2HDh3jyeXg',
    appId: '1:661269225469:android:6c8d058737f964fccb4394',
    messagingSenderId: '661269225469',
    projectId: 'whatsappclone-94efa',
    storageBucket: 'whatsappclone-94efa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsgF4YLa4_sfAxkIcAz77bCnqQzDHhoIk',
    appId: '1:661269225469:ios:72def327e81b6ba4cb4394',
    messagingSenderId: '661269225469',
    projectId: 'whatsappclone-94efa',
    storageBucket: 'whatsappclone-94efa.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsgF4YLa4_sfAxkIcAz77bCnqQzDHhoIk',
    appId: '1:661269225469:ios:d0ce5318c22362f5cb4394',
    messagingSenderId: '661269225469',
    projectId: 'whatsappclone-94efa',
    storageBucket: 'whatsappclone-94efa.appspot.com',
    iosBundleId: 'com.example.whatsappClone.RunnerTests',
  );
}
